language: cpp

compiler:
  - gcc

sudo: required
dist: precise

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - libboost1.60-dev

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && ctest
