language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

before_install:
  - | 
    wget http://downloads.conan.io/latest_debian -O conan.deb
    sudo dpkg -i conan.deb
  - export BOOST_ROOT_DIR=
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - | # Setup the BOOST_ROOT
    export BOOST_ROOT=$HOME/boost_root
    mkdir -p $BOOST_ROOT/stage
    ln -s /usr/lib/x86_64-linux-gnu $BOOST_ROOT/stage/lib
    ln -s /usr/include/boost $BOOST_ROOT/boost

before_script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake ..

script:
  - make && ctest

notifications:
  email: false
